### ISSUE TITLE
Update kubernetes and ubuntu version to support cgroup2

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/architecture#550]
Kubernetes: `1.25.x`
Ubuntu: `22.04` (jammy)

JRE Docker image: `eclipse-temurin:17-jammy`

https://kubernetes.io/docs/concepts/architecture/cgroups/

**Comment by theferrit32** [comment]
These changes have been applied, but if we ever delete the dev node pool before the Regular branch is updated to k8s `1.26.x`, it will probably reset this configuration to the default cgroup v1. I will check in the nodeconfig that was applied via the CLI

**Comment by theferrit32** [comment]
I think I'll just not worry about adding the applying of the nodeconfig to terraform, since GKE is updating to 1.26 next month.

https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-26

**Comment by theferrit32** [comment]
Actually not even going to add it to git. This issue will be the documentation:
```yaml
# https://cloud.google.com/kubernetes-engine/docs/how-to/node-system-config#cgroup-mode-options
# https://cloud.google.com/kubernetes-engine/docs/how-to/node-system-config#add

# gcloud container node-pools update main-pool --cluster genegraph-dev --region us-east1-b --system-config-from-file node-pool-configuration.yaml

linuxConfig:
  cgroupMode: 'CGROUP_MODE_V2'
```
