### ISSUE TITLE
Install external-secrets in the genegraph-dev cluster

### ISSUE THREAD

**Issue by sjahl** [clingen-data-model/architecture#9]
We'd like to trial [kubernetes-external-secrets](https://github.com/external-secrets/kubernetes-external-secrets#gcp-secret-manager) in the genegraph-dev cluster. External-secrets is a kubernetes controller that synchronizes GCP secrets with k8s secrets inside our cluster.

The premise here is that we create and manage our secrets (and versions of those) in the GCP Secret Manager. In our architecture repository, we then create ExternalSecret manifests, which instruct the external-secrets controller on what our secrets in GCP are called, and what we'd like them to be called when imported to the cluster as k8s secrets. The controller is then responsible for syncing to the secrets as we add/change/update them.

### Success Criteria

The goal for this work is to deploy external-secrets into genegraph-dev so that the team can test it. When complete, a developer should be able to create a secret in the clingen dev GCP project, then `kubectl apply` an ExternalSecret manifest from the architecture repository, and have the desired kubernetes secret appear for use in the genegraph-dev cluster.

### Example

Given a GCP Secret called 'genegraph-dev-secret-string'

```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: genegraph-dev-frobulator-api-key # name of the k8s external secret and the k8s secret
spec:
  backendType: gcpSecretsManager
  projectId: clingen-dev
  data:
    - key: frobulator-api-key # name of the GCP secret
      name: api-key # key name in the k8s secret
      version: latest # version of the GCP secret
```

Should result in a kubernetes Secret that can be retrieved with `kubectl get secret genegraph-dev-frobulator-api-key -o jsonpath='{.data.apikey}' | base64 -D`
